const protectedMemberConfig = {
  title: "Members",
  descriptionUpdate: "Update members",
  description: "Manage your members",
  delete: "Delete",
  edit: "Edit",
  update: "Update",
  submit: "Submit",
  questionDelete: "Are you sure you want to delete this member?",
  warning: "This action cannot be undone.",
  cancel: "Cancel",
  confirm: "Confirm",
  tableHeader: ["Member", "Date", "Action"],
  updateMember: "Update Member",
  newMember: "New Member",
  successDelete: "Member deleted.",
  successCreate: "Member created.",
  successUpdate: "Member updated.",
  errorCreate: "Couldn't create member.",
  errorDelete: "Couldn't delete member.",
  errorUpdate: "Couldn't update member.",
  author: "Author",
  pleaseWait: "Please wait...",
  untitled: "Untitled",
  formName: "Name",
  placeholderName: "Please provide a name for the member",
  formEmail: "Email",
  placeholderEmail: "Please provide an email address for the member",
  formDescription: "Description",
  placeholderDescription: "Please provide a description for the member",
  formActive: "Is Active",
  placeholderActive: "Please select an option",
  formApproved: "Is Approved",
  placeholderApproved: "Please select an option",

};

export default protectedMemberConfig;
