const protectedEventConfig = {
  title: "Events",
  descriptionUpdate: "Update your event",
  description: "Manage your events",
  delete: "Delete",
  edit: "Edit",
  update: "Update",
  questionDelete: "Are you sure you want to delete this event?",
  warning: "This action cannot be undone.",
  submit: "Submit",
  cancel: "Cancel",
  confirm: "Confirm",
  tableHeader: ["Post", "Date", "Action"],
  updateEvent: "Update event",
  newEvent: "New Event",
  successDelete: "Event deleted.",
  successCreate: "Event created.",
  successUpdate: "Event updated.",
  errorCreate: "Couldn't create event.",
  errorDelete: "Couldn't delete event.",
  errorUpdate: "Couldn't update event.",
  author: "Author",
  pleaseWait: "Please wait...",
  untitled: "Untitled",
  aboutPlaceholder: "What is the event about?",
  formName: "Name",
  formSlug: "Slug",
  placeholderName: "Please provide a name for your event",
  placeholderSlug: "Please provide a slug for your event",
  formAddress: "Address",
  placeholderAddress: "Please provide an address for your event",
  formPlace: "Place",
  placeholderPlace: "Please provide a place for your event",
  formAbout: "About",
  placeholderAbout: "Please provide what the event is about",
  formDate: "Date",
  placeholderDate: "Please provide the date of the event",
  formStartTime: "Start Time",
  placeholderStartTime: "Please provide the start time of the event",
  formEndTime: "End Time",
  placeholderEndTime: "Please provide the end time of the event",
  formRegistrationLink: "Registration Link",
  placeholderRegistrationLink:
    "Please provide a registration link for your event",
  generateSlug: "Generate slug",
  coverImageTitle: "Cover Image",
  coverImageDescription: "You can upload one cover image.",
  placeholderImage: "Image url",
  shortDescriptionTitle: "Short description",
  shortDescriptionDescription: "Update your event's short description",
  placeholderDescription: "Please provide a short description of your event",
  errorMessagesDeleteImage: "Error deleting image",
  errorMessageImageUpload: "Error uploading image",
  successMessagesDeleteImage: "Image deleted",
  successMessageImageUpload: "Image uploaded",
  formImageNote: "Only JPG, PNG and GIF files are allowed",
  formImageUploadFile: "Upload a file",
};

export default protectedEventConfig;
